### PR TITLE
animations rework

### PR DESCRIPTION
**Pull request by stryju**
par 1 (*as I see it*) of different handling of animations (relying on `ngAnimate` fully)

as discussed in https://github.com/zurb/foundation-apps/issues/313#issuecomment-67163343, this one tackles states only

- removed the animation
- augmented `uiState` directive
- tweaked the state augmentation with `animations` property

### CODE REVIEW

**Comment by AntJanus** [comment]
@stryju I'm gonna go ahead and pull this locally and try to do some work on it. I'm not sure how I can work on this collaboratively since this is off your repo but I'll give it a shot.

Just some notes and todos:

* [ ] absolute positioning of parents
* [ ] backface visibility in animation
* [ ] testing on various browsers
* [ ] move absolute positioning to utilities (this is my fault, I've no idea why i didn't move it)

**Comment by stryju** [comment]
well, since it's OS, just branch of my branch? :D

**Comment by AntJanus** [comment]
That's what I'll do! :) I've no idea if I'll have to open up a PR for it on your project or what. This stuff is pretty confusing.

I guess we'll deal with that as we go.

**Comment by stryju** [comment]
:+1:

**Comment by gakimball** [comment]
Closing in favor of #386.

**Pull request closed without merging**
