### PR TITLE
[Ready for review] Angular refactor

### PR DESCRIPTION
**Pull request by AntJanus**
Refactor based on #262 

From the issue:

> Currently, Angular is working based off how AngularJS itself keeps up their code style; however, it doesn't follow some of the best practices for Javascript in general or what people have found useful. John Papa has [a great styleguide](https://github.com/johnpapa/angularjs-styleguide) and Todd Motto has [another one](http://toddmotto.com/opinionated-angular-js-styleguide-for-teams/).

To dos:
- [x] abstracting out interchange 
- [x] move components into `/components` with template and JS
- [x] move foundation init to a more proper module. FoundationInit works directly with dynamic routes, no need to keep it as a general `init`.
- [x] Move default controller into dynamic routes module
- [x] make everything work in new structure
- [x] fix tests
- [x] add `.jshint` and fix errors.

Styleguide:
- [x] IIFE
- [x] use strict
- [x] function declarations over function expressions (urgh, not looking forward to trying to do this)
- [x] manual deps injection (rather than using the array notation, using the injector, not a fan but can't have declarations instead of expressions without array notation)
- [x] using require on more complex directives (tabs, accordion, etc.). Use `^^` for parent requirements
  .
  Finally:
- [x] merge master

### CODE REVIEW

**Comment by jaysonminard** [comment]
And the status of this then is "on hold" or "forgotten" ?

**Comment by gakimball** [comment]
@jaysonminard This refactor has been in place since 1.0.2. A big thing to put in a patch number, yes, but it was very early in the framework's life, and we needed it out anyway. We're putting out 1.1 tomorrow most likely.

**Comment by japhar81** [comment]
@AntJanus nice work! One question, how the heck does one write unit tests for custom controllers? I wrote a dead-simple controller;

```
(function () {
    'use strict';
    angular.module('application')
        .controller('HomeController', HomeController)
    ;
    HomeController.$inject = ['$scope', '$stateParams', '$state', '$controller'];
    function HomeController($scope, $stateParams, $state, $controller) {
        angular.extend(this, $controller('DefaultController', {
            $scope: $scope,
            $stateParams: $stateParams,
            $state: $state
        }));
        $scope.test = "test1";
    }
})();
```

And what I thought was an appropriate karma test to match;
```
'use strict';

describe('Unit: HomeController', function() {
    beforeEach(module('application'));

    it('should exist', inject(function(FoundationApi) {
        expect(FoundationApi).not.toEqual(null);
    }));

    var ctrl, scope;

    beforeEach(inject(function($controller, $rootScope) {
        scope = $rootScope.$new();
        ctrl = $controller('HomeController', {
            $scope: scope
        });
    }));

    it('should have $scope.test set to test1',
        function() {
            expect(scope.test).toEqual("test1");
        });
});
```

However, I always get; 
```
TypeError: Cannot read property 'replace' of null
	    at Object.init (/Users/hzektser/IdeaProjects/foundationTemplate/bower_components/foundation-apps/dist/js/foundation-apps.js:630:79)
	    at mqInitRun (/Users/hzektser/IdeaProjects/foundationTemplate/bower_components/foundation-apps/dist/js/foundation-apps.js:596:12)
	    at Object.invoke (/Users/hzektser/IdeaProjects/foundationTemplate/bower_components/angular/angular.js:4203:17)
	    at /Users/hzektser/IdeaProjects/foundationTemplate/bower_components/angular/angular.js:4025:71
	    at forEach (/Users/hzektser/IdeaProjects/foundationTemplate/bower_components/angular/angular.js:323:20)
	    at Object.createInjector [as injector] (/Users/hzektser/IdeaProjects/foundationTemplate/bower_components/angular/angular.js:4025:3)
	    at Object.workFn (/Users/hzektser/IdeaProjects/foundationTemplate/bower_components/angular-mocks/angular-mocks.js:2425:52)
	TypeError: Cannot read property 'test' of undefined
	    at Object.<anonymous> (/Users/hzektser/IdeaProjects/foundationTemplate/tests/components/home/HomeController.tests.js:21:25)
```

**Comment by stryju** [comment]
@japhar81 http://plnkr.co/edit/tHGew1cst9OYwV6ib4lg?p=preview

**Comment by stryju** [comment]
can't find the issue, @japhar81 - will check out later :)

**Comment by japhar81** [comment]
If a repro case will help, here's my repo: https://github.com/japhar81/foundationTemplate

```
git clone https://github.com/japhar81/foundationTemplate
cd foundationTemplate
npm install
bower install
gulp
node_modules/karma/bin/karma start karma.config.js --log-level debug --single-run
```

**Comment by AntJanus** [comment]
@japhar81 I'm not sure why you'd get the error. Have you tried tracking it down the stack? I'll look at it sometime tomorrow or this upcoming week and will let you know what I come up with.

**Comment by stryju** [comment]
@japhar81 it seems that the issue you're having is related to `mqInit.init();` call - this fails, not your tests :-)

**Comment by japhar81** [comment]
@stryju that's good to know, but.. how do i make the tests work :)

**Comment by ryanburnett** [comment]
@AntJanus Are you still planning on merging this in?

**Pull request merged**
