### PR TITLE
Allow running dynamic routing more than once in a build

### PR DESCRIPTION
**Pull request by soumak77**
Updates to allow appending to the file versus replacing the file on each run of the plugin

### CODE REVIEW

**Comment by gakimball** [comment]
Could you give an example of how you'd use this new feature?

**Comment by soumak77** [comment]
First off, I switched to using F4A for all apps I develop at my company.  In order to make reusing modules across apps easy, I created a single module to store all common app logic and components.  Since I use F4A as the core of my apps, this single module is allowed to also contain front matter to pass through the dynamic routing F4A provides.  An example of this is my shared account module which houses all components for account management and is set up so that it uses the url /account/... for all the states in that module.  Some of the views in that module use front matter to define their states.

I wrote a small shell script which is used to build any of my apps.  That script first builds the shared module then builds the desired app.  The way my build is set up, it requires running the dynamic routing against the shared module code first, then later against the app code.  I needed a way such that I could combine the output of the two runs, thus my proposed PR.

**Comment by soumak77** [comment]
I'm wondering maybe a different approach could be used.  Currently a global variable is used to hold the routes and it is used in the config function of the foundation.dynamicRouting module js file.  I think it could be changed so that the module config call is removed from the js file and each run of the dynamic routing plugin produces the following snippet of code:
```js
angular.module('foundation.dynamicRouting').config(['FoundationStateProvider',
  function(FoundationStateProvider) {
    FoundationStateProvider.registerDynamicRoutes(/* routes */);
  }
]);
```
This way regardless of how many times one needs to run the plugin, the code outputted is always the same.  It'll also remove the need for a global variable.

**Comment by AntJanus** [comment]
@soumak77 if I understand this correctly you're proposing the plugin:

1. creates a module that sets up the routes
2. appends the routing to an existing file rather than creating a new one that just holds the routes.

Is that correct?

On the first point, I saw that you're using `fs.appendFile` for both non-module and module declaration. Does append file write a file if it doesn't exist?

The code looks sound. I'd suggest that the `writeData` function gets the `appendingToFile` option passed in order to avoid scoping problems.

**Comment by soumak77** [comment]
@AntJanus Yes ```fs.appendFile``` will write the file if it doesn't exists ([see the docs](https://nodejs.org/api/fs.html#fs_fs_appendfile_filename_data_options_callback)).

The suggestion in my last comment was not to have the plugin create a module that sets up the routes as that module already exists with **foundation.dynamicRouting**.  The suggestion is to simply have the plugin output code that calls the config method on this existing module versus storing the routes in a global variable and using that variable in the config call in *foundation.dynamicRouting.js*.  This does not require appending to an existing file, though it would change the workflow and require the routes js file(s) be included AFTER the foundation js files, as the routes js file(s) would require the **foundation.dynamicRouting** module to exist.  The code as is in my PR does not require this workflow change since it still uses the global variable.

**Comment by soumak77** [comment]
After reviewing the code again, I believe the **append** option I added to the plugin is misleading as the code is now using ```fs.appendFile``` instead of ```fs.writeFile```.  This means that if I pass false for the append option (or don't specify it at all) and the file I provide exists, the file is still going to be appended, however, since the appended code will include the ```var``` statement, it will act the same as if the file was overridden, but have useless code at the top of it.  Is there any reason to believe someone would want to have an existing routes file overridden versus always appending to it if it exists?  The only thing I could think of is if they don't clear their build output directory and the routes files from a previous build still exists when running the next build.

**Comment by gakimball** [comment]
@soumak77 So what we're trying to solve is the issue of incremental builds, where you may not be passing every file through the router. Your use case seems somewhat specific, but from a Gulp perspective, being able to support partial builds (like using `gulp-cached` to only pass modified files through a stream) would be useful.

One issue I see with your current approach is that the more you append, the more `foundationRoutes.concat` calls you get in your code, and the plugin right now probably can't differentiate between a route being *added* versus *changed*, so if you ran it too many times the file would become larger than necessary. To be sure, though, actually reaching into the existing file and modifying the JS object in there would be tricky, as you wouldn't know the exact formatting (uglified or not? etc.)

I wonder if you can store the routes in memory and just reference that when re-generating the routes file. There are some Node modules that would let you store the data after the process exists.

I like the idea of using module configuration, since that will pull that `foundationRoutes` variable out of the global scope. It's worth noting that we'd like to move the routing plugin into its own npm module in a future version of the framework, because we realized having a node module in a Bower package is a little weird. I'll take the blame for initially suggesting that ;)

To do it right, we would probably introduce the module in 1.2, but keep the old one in place until 1.3, when we formally deprecate it by removing the `bin` folder from the repo. Your idea requires changing the order in which files are loaded in the HTML (libraries, then routes, then boostrap), so a new version of the plugin could introduce these breaking changes.

If you're interested in working on those bigger changes to the plugin, I can set up the new repo with some test files set up and you can hack away at it.

**Comment by soumak77** [comment]
@gakimball sure, I don't mind working on those plugin changes

**Comment by gakimball** [comment]
@soumak77 You're the best! Thanks so much for your interest in contributing to the framework. Once again, we don't have a timeline for 1.2, so don't fret about getting it done right now.

[Here's the standalone module.](https://github.com/zurb/front-router) To recap, here are the goals of a new version:
  - Support incremental builds: the parser needs to be able to print a routes object without passing every file through every time.
  - Use module configuration instead of a global variable to print routes.
  - Keep it backwards-compatible! For version 1.2, the `foundation.dynamicRouting` module should work with the old *and* new router. For version 1.3 we can drop support for the old router.

**Pull request closed without merging**
