### PR TITLE
Fixes #569

### LINKED ISSUE #569: Iconic images don't work with directives
When using the following code
```html
<img zf-iconic="" ng-show="..." />
```
The ```img``` element is replaced with a ```svg``` element.  The ```ng-show``` attribute is not copied from the ```img``` element to the ```svg``` element.  This also goes for the other directives I've tried ```ng-hide```, ```ng-show```, and ```ng-click```.  I would guess that this is true for all directives.

### PR DESCRIPTION
**Pull request by soumak77**
Copies attributes from img to svg after injection

### CODE REVIEW

**Comment by soumak77** [comment]
I was going to write up another PR for a068352b59e8549152ca4bbeedce8be03e60fd51, however, a fix was required in this PR to get the changes working so I figured I would just combine them.  The latest change adds the ability to provide dynamic icon attributes.  Here's an example of its usage:

```js
$scope.actions = [{
  icon: 'account',
  iconAttrs: {
    state: 'login'
  }
},{
  icon: 'account',
  iconAttrs: {
    state: 'logout'
  }
},{
  icon: 'chevron',
  iconAttrs: {
    direction: 'right'
  }
},{
  icon: 'chevron',
  iconAttrs: {
    direction: 'left'
  }
}];

// this is just to showcase the dynamic icons working, though a more common case would
// have some trigger which changes the icon (e.g. once you logout, switch icon to login)
var actionNum = 0;
$scope.action = $scope.actions[0];

$scope.updateAction = function() {
  $timeout(function() {
    actionNum++;
    if (actionNum == $scope.actions.length) {
      actionNum = 0;
    }
    $scope.action = $scope.actions[actionNum];
    $scope.updateAction();
  },3000);
};
$scope.updateAction();
```

Now you can use a dynamically updating icon in your view!
```html
<img zf-iconic="" dyn-icon="action.icon" dyn-icon-attrs="action.iconAttrs"></img>
```

This also works for static icons as shown below (though it would probably make more sense just use to use appropriate 'data-' in this case).
```html
<img zf-iconic="" icon="chevron" icon-attrs="{ 'direction': 'left' }"></img>
```

If you have you have a static icon, but still want to use the scope to store your icon info, you could also do this:
```html
<img zf-iconic="" icon="{{ action.icon }}" icon-attrs="{{ action.iconAttrs }}"></img>
```
While **dyn-icon** and **dyn-icon-attrs** would work in the above case, if you know your icon will never change, the above method is preferred as using dyn-* will cause watchers to be set up, which are not needed if the icon never changes.

**Comment by gakimball** [comment]
This is really interesting, do you think you could add a section to the Iconic documentation page that explains this, with a live demo and code example?

**Comment by soumak77** [comment]
@gakimball Sure no problem, I'll knock that out right now!

**Comment by gakimball** [comment]
Thanks!

**Comment by gakimball** [comment]
One last question, the last section, "Delay Loaded Icon" shows two code examples, one where the icon doesn't render and one where it does. Is it possible to just have the second example, since it's the one that implements the fix you describe? Our documentation should skew towards having one example to show how to do something. If you'd never use the first example, then we can probably drop it.

**Comment by soumak77** [comment]
Yeah I'm fine dropping the first example

**Comment by gakimball** [comment]
Sounds good, I'll update it.

**Pull request merged**
