### PR TITLE
Allow ModalFactory to create dialog modals

### PR DESCRIPTION
**Pull request by soumak77**
Extend ModalFactory configuration to allow creation of dialog modals by
adding dialog class to dynamically generated element.  This change allows creating a dialog modal via the ModalFactory by providing the following configuration:
```js
var modal = new ModalFactory({
  dialog: true,
  ...
});
```
This PR and #561 should be reviewed together as they both deal with adding classes to the generated modal.  This PR is specific to allowing the **dialog** class to be added, while the other is generic and allows any class to be added.

### CODE REVIEW

**Comment by gakimball** [comment]
This should be fine, although one thing we want to avoid in the future is hard-coding class names. All of the Foundation frameworks are written in Sass mixins, which means you can rip out our entire class structure and replace it with your own if you want. With that in mind, JS plugins should avoid adding or referencing built-in classes, because we can't guarantee that the user is using them.

To be sure, though, we do this a lot in Foundation for Apps right now. It's also trickier with Angular, because our components are these templates that you just drop in. In Foundation for Sites it's easier, because the user just drops a bunch of data attributes onto existing markup.

The framework is very new, though, and for specific components like this not many people are probably using the mixins yet. They're most commonly-used for the grid, and that's also arguably the place they're most valuable.

So if we merge in #561, will this work as-is, or will you need to make another change?

**Comment by soumak77** [comment]
@gakimball after thinking it over, I think there is an issue with #561 in that it would overwrite any existing classes on the element.  Perhaps switch the ```config['class']``` prop from being a string to being an array of strings and add all classes provided versus just overwriting the class attribute.

**Comment by gakimball** [comment]
@soumak77 If we pull in #561, could you merge/rebase this PR and get the proper fix in to we can reconcile the two?

**Comment by soumak77** [comment]
@gakimball Sure no problem

**Comment by gakimball** [comment]
Alright, merged in #561.

**Comment by soumak77** [comment]
Still familiarizing myself with git, but I think I did that correctly

**Comment by soumak77** [comment]
Just noticed I messed up the merge for the switch statement, fixing now

**Comment by gakimball** [comment]
Nice, so it's solid, then?

**Comment by soumak77** [comment]
Yeah, tested after merging and works greats.  Docs might need a little cleanup, but framework functionality is good.

**Comment by gakimball** [comment]
Awesome, thanks!

**Pull request merged**
