### PR TITLE
Foundation Adapter

### PR DESCRIPTION
**Pull request by AntJanus**
Foundation Adapter is an effort to simplify the FoundationApi and make things easier on the user.

Todo:

- [x] create facades for every element that add element-specific methods (like `addTab` or `notify`).
- [x] provide an adapter to hide FoundationApi implementation and add sugar for more frequently used features (~~like `getMediaQueries`~~).
- [x] make this not look like spaghetti code.

### CODE REVIEW

**Comment by AntJanus** [comment]
@circlingthesun this is the start of the adapter I was thinking about and I'll start porting it to the facades (I still want to have a central adapter). So the facade would look something like:

````js
  FoundationModal.$inject = ['FoundationApi', 'ModalFactory'];

  function FoundationModal(foundationApi) {

    var service    = {};

    service.activate = activate;
    service.deactivate = deactivate;
    service.newModal = newModal;

    return service;

    function activate(target) {
      foundationApi.publish(target, 'show');
    }

    function deactivate(target) {
      foundationApi.publish(target, 'hide');
    }

   //sugar for ModalFactory so that it doesn't have to be accessed directly
   function newModal(config) {
     return new ModalFactory(config); 
   }
  }
````

**Comment by circlingthesun** [comment]
That looks good. You could also add the code from ModalFactory into the adaptor.

**Comment by AntJanus** [comment]
I'd like to keep them separate just in case. But cool. I'll go ahead and code all this up.

**Comment by AntJanus** [comment]
Hey guys, this is good to be merged in if anyone wants to go ahead and do it :)

**Pull request merged**
