### PR TITLE
Menu Bar component

### PR DESCRIPTION
**Pull request by gakimball**
The Menu Bar should be a flexible, highly-customizable, all purpose menu bar. Its origins are in the Icon Bar in Foundation 5, but this component will have more options for icon placement and secondary features like labels.

**Features:**
- [x] Horizontal and vertical orientation, with breakpoint classes for both
- [x] Icon positioning (left, top, right, bottom)
  - [x] Breakpoint classes for icon positions
- [x] Spacing options (e.g., left-aligned items, evenly-spaced items)
- [x] Count labels (i.e., unread message count)
- [x] Coloring classes (primary and dark)

**Component requirements:**
- [x] Settings variables
- [x] Layout mixins
- [x] Style mixin

### CODE REVIEW

**Comment by etcook** [comment]
Do you see the menu bar in F4A coming into parity with topbar from F4S? There isn't much in the way of built in navigation capability in F4A.

Thoughts?

**Comment by gakimball** [comment]
Yep, we have plans to improve menu bar, namely by adding support for sub-menus and improving the switch to mobile.

That being said, we're also working on Foundation for Sites 6 right now, and we're trying to overhaul the top bar. We think it's inflexible and hard to customize, since it's basically designed to do one thing well. We're trying to unify patterns between the two frameworks, so whatever ideas we have for Sites will likely make it back to Apps. The main difference is that the Apps menu bar will be written in Flexbox.

**Comment by etcook** [comment]
@gakimball Thanks for the update. You've whet my palette. Looking forward to it!

**Comment by philippeluickx** [comment]
Design suggestion:

I currently have a top navigation section (homepage, profile link, etc.) and a footer navigation section (blog, contact, privacy,...). They are sticky and this works fine on large screens.
On mobile it is horrible, as together they already take up almost half of the screen. When keyboard opens, nothing of the actual site is left.

Would it be possible to have menu(s) on large screens transform to drawers (the mobile paradigm)? Sideways swipe and a sandwich button would bring that drawer up. Bonus if both menus would be combined in one drawer.

**Comment by gakimball** [comment]
@philippeluickx We'll need to take a hard look at the keyboard thing pretty soon here, because it does seem to work poorly with certain layouts, especially ones with a fixed footer and header. It's also possible that different mobile platforms handle the keyboard different with regards to calculated screen size, how it overlays the page, and so on.

**Pull request merged**
