### PR TITLE
Added alignment classes to menu bars in order to align menu items

### PR DESCRIPTION
**Pull request by tatemz**
These alignment classes will allow menubar menu items to "float"  right, center, justified, and spaced.

### CODE REVIEW

**Comment by tatemz** [comment]
Darn git-flow...

**Comment by gakimball** [comment]
Could you use the plain `justify-content` property instead? Using a grid mixin here means the menu bar would have a dependency on the grid component, and ideally no component is dependent on another (unless it's a sub-component, like button group).

**Comment by tatemz** [comment]
Understandable. Thanks for the tip. Will update.

**Comment by tatemz** [comment]
Looks like you guys have a bad gulpfile... `ReferenceError: autoprefixer is not defined`

Perhaps add `var autoprefixer = require('gulp-autoprefixer');`

**Comment by gakimball** [comment]
Ah yeah, it's a typo in the `node-sass` task. Changing [this line](https://github.com/zurb/foundation-apps/blob/18b168b9f1f9c74aa4a25b65cc421722505eaacf/gulpfile.js#L150) of the code will fix it. `autoprefixer` should be `$.autoprefixer`.

**Comment by gakimball** [comment]
Thanks for making the changes. :)

**Pull request merged**
