### PR TITLE
Swipe directives

### PR DESCRIPTION
**Pull request by soumak77**
Implementation based off [ng event directives](https://github.com/angular/angular.js/blob/master/src/ng/directive/ngEventDirs.js#L3).

### CODE REVIEW

**Comment by soumak77** [comment]
Implements #513

**Comment by soumak77** [comment]
@gakimball After playing around with this feature I feel there needs to be a way to configure the directives to allow changing of the threshold and velocity values passed to Hammer.  There are a couple of ways this can be achieved.  First off, default settings should be configured via a provider, not hard coded in the directive, to allow application wide overrides for the swipe directives.  Fine tuning specific uses of the swipe directives can be done via element attributes (**zf-swipe-threshold** and **zf-swipe-velocity**).  In both cases, I'm thinking there needs to be some abstraction so that users don't need to know the exact values to pass to Hammer.  For instance we could allow passing of values ***slow*, *normal*, and *fast* for zf-swipe-velocity**, which are converted to Hammer values under the hood (similar to how Motion UI abstracts the exact values used in the CSS animations).  Similarly to express distance, we could use ***short*, *normal*, and *far* for zf-swipe-threshold**.  Both the provider and attribute solutions should allow passing of numerical values that get directly passed to Hammer, in the event the named options don't fit a developer's needs.  The provider can also allow a developer to change the meaning of the string values or add their own.  This way I can change *slow*, *normal* and *fast* to fit the needs of my application as well as add *super slow* and *super fast* as additional options.

I'll work on the updates above once an interface has been agreed upon.

**Comment by soumak77** [comment]
@gakimball Sorry to be a pest, but any thoughts on this feature?  I'd like to finalize the PR so it can be in an upcoming release.

**Comment by gakimball** [comment]
@soumak77 Hey, no problem! We're going to try and square away some of the bigger Apps issues and pull requests this week.

**Comment by soumak77** [comment]
@gakimball I wasn't trying to get it into the next release, just something in the future like 1.2 or 1.3.  Do you or your team already have something in mind for this type of feature or can I take it further and implement the things I noted above?

**Comment by gakimball** [comment]
@soumak77 Since it's a feature, we can save it for 1.2. We don't have a timeline for a 1.2 right now, but you'll have plenty of time to work on it. We weren't planning on implementing this feature specifically, so you can definitely own it.

If you give me one more day to review this with the team, I'll get you some feedback. :)

**Comment by soumak77** [comment]
@gakimball sounds good, thanks!

**Comment by soumak77** [comment]
@gakimball any feedback on this?  I'll implement my ideas above for you and your team to review when find the time

**Comment by soumak77** [comment]
I know you guys are working on 1.1.1 right now so no rush, but when you find the time please provide some feedback on this PR so we can get it stabilized for 1.2.  The code is stable, but the exact values to use for named distances and named velocities need some work (if in fact that ends up being the way the swipe directives are configured).

**Comment by soumak77** [comment]
fix has been made in https://github.com/base-apps/angular-base-apps

**Pull request closed without merging**
