### PR TITLE
Interchange directives

### PR DESCRIPTION
**Pull request by soumak77**
This PR replaces #539, which implements #538

### CODE REVIEW

**Comment by soumak77** [comment]
One thing to point out here is that this solution does NOT provide a way to make the sizing classes (i.e. *small-#*, *medium-vertical*, *large-horizontal*, etc) work off element queries instead of media queries.  So if you use one of the added directives as an element query and the attached element contains a child grid-block with one of the sizing classes, the sizing of that block is based on the media and not the element.

Getting the sizing classes to work off element queries is the key to getting a truly responsive framework.  I played around with it last night and found a way I can get it so that if you add a specific directive to an element (e.g. *zf-responsive-block*), it can update all child elements within it, so that each of those elements are configured to perform element queries.  The directive recursively travels down the DOM until all elements within the original *zf-responsive-block* have been configured.  The result of running the element query will cause a class to get added to the element (e.g. *is-small*, *is-medium*, *is-large*).  I now need to figure out how to get the breakpoint mixin to respect these classes so that the media query is not run if an element has one of those classes since the presence of those classes indicate an element query was already run and a media query is not required.

The above is going to take a lot of effort to get right, so I'll continue that effort in a separate PR (which will be posted once I have something worth sharing).

**Comment by soumak77** [comment]
@gakimball Turns out it wasn't too difficult to get the sizing classes to work based off element queries instead of media queries (at least for the use cases I tried).  I included those changes in this PR so that they could be reviewed along with the interchange directives as both rely heavily on the media query service.  Both changes still need some cleaning up as they are hard coded to only work with *small*, *medium*, and *large* named classes, versus dynamically adjusting to whatever the developer chooses to use as their named breakpoints.  I think the code should also be refactored into different files as everything currently resides in the interchange js and html file.  I'm not sure of the desired workflow for such changes so I'll wait to hear back on your guidelines.

**Comment by soumak77** [comment]
@gakimball I've been using the ```zf-if-*``` directives throughout my code in place of ```zf-interchange``` and really like how easy it is to specify exactly when to show something based off a media query.  It also removes the extra parent element (e.g. ```<div>```) added by ```zf-interchange```.  If there is any desire to pull in those changes without element query support, let me know and I can split up the PR.  I've noticed some issues with element queries while playing around with them (specifically that the element query is not rerun in some cases), so it would probably be better left for a 1.3 or 2.0 release since a lot of testing will be required to ensure it's fully working.  I have a future project in mind that would greatly benefit from element queries so I hope I can get that feature stabilized at some point so it can be included in F4A.

**Comment by soumak77** [comment]
@gakimball I stabilized the element queries by including this library: https://github.com/sdecima/javascript-detect-element-resize

**Comment by gakimball** [comment]
The team looked over this today, good stuff!

We like the `zf-if` concept as a different way to do visibility, but not necessarily as a replacement for Interchange. The benefit of Interchange is that visibility within a set of elements is mutually-exclusive—only one element within an Interchange element can be displayed. In some of your examples, each element in a set needs to use an `only` version of a media query, otherwise every element would appear at once on a large screen.

Our main piece of feedback for the `zf-if` concept is that you could simplify the directive by having just one, called `zf-if`, and then read the name of the media query off of the value of the directive, like so:

```html
<div zf-if="medium"></div>
<div zf-if="small only"></div>
```

This solves another issue which this feature would need to address, which is that the breakpoint names are hard-coded. Right now small, medium, and large are built-in, but the framework also has xlarge and xxlarge, *and* the user can change the names of the media queries, or add new ones. You can access them through the `foundation.mediaqueries` module. With this in mind, a more generic `zf-if` directive makes sense, because then you're just parsing a string and checking it against the global media query list.

As for element queries, we're not sure we're ready to implement them quite yet. Also, we don't want to add another external library to the framework right now. Foundation for Apps already has seven dependencies, so we'd like to hold off on adding any new ones until we're ready for a v2 of the framework.

**Comment by soumak77** [comment]
@gakimball thanks for the feedback.  I'll revert that code related to element queries from this PR.

I like the idea of having a string passed in to specify the media queries for all the reasons you called out.  I'll make the necessary changes to the ```zf-if```, ```zf-hide``` and ```zf-show``` directives.

**Comment by soumak77** [comment]
Is this something that could get into the next release or does it need to wait until a major release?

**Comment by gakimball** [comment]
Our next release will be a patch, and then probably a minor release after that (1.2). Sorry for making you wait so long! :) The work you're doing is fantastic.

**Comment by soumak77** [comment]
@gakimball After making the updates to the directives and integrating them into my existing published app, I noticed an issue with the following markup I had that worked with my old implementation:
```html
<div zf-if="not large"/>
<div zf-if="large"/>
```
The ```large``` will display on large **or larger** screens and the ```not large``` will show if the device is **not** large.  

This works great so long as you're on a large or smaller device.  If you go into xlarge, both will end up being displayed.  What I really need is for the ```not large``` to display if the device is **medium or smaller**.  As you mentioned in one of your comments, the existing interchange mechanism supports this, however, I still would prefer to use the zf-if style, so to accommodate that use case, there needs to be a way to specify that I want something to show up if the device is _____ or smaller.

Do you have any preference on the verbiage used to specify something is _____ or smaller?  Possible solutions for declaring something be shown for large or smaller could be: ```<= medium```, ```less than or equal to medium```, ```medium or smaller```, ```< large```, ```less than large```, or something else.

As of now the following verbiage exists.  Placement of ```not``` and ```only``` do not matter (i.e. can be before or after named breakpoint):
```large```: Show for large or larger (shown for large, xlarge, xxlarge)
```not large```: Show if not large (shown for small, medium, xlarge, xxlarge)
```large only```: Show if large only (shown for large)

**Comment by soumak77** [comment]
I added what I needed to the directives.  I used the "or smaller" verbiage, though that can be changed if desired.  I also moved all media query logic out of the directives and into the service for easier reusability.

**Pull request merged**
