### PR TITLE
Modal factory

### PR DESCRIPTION
**Pull request by AntJanus**
Goals:

- [x] allow modals to be created on the fly with no on-page markup
- [x] build with templates and straight HTML
- [x] activate/deactivate modals straight through the factory
- [x] do not create until activated
- [x] there might be some need for a destroy method, too

### CODE REVIEW

**Comment by circlingthesun** [comment]
So if I read this right this will allow you to dynamically create a modal and let the calling code open and close the modal. What if I need the modal to close itself from a button inside the modal or something more complex? One way of allowing that to happen is setting ```deactivate``` function on the scope before linking the modal. This way I can call ```$scope.deactivate()`` inside the modal.

**Comment by circlingthesun** [comment]
It would also be nice to return results from a modal. You can do this by having the ```activate()``` function return a promise and have the ```dismiss(result)``` function take one parameter that resolves that promise.

returning a promise

It would also be nice if the open call to the modal could return a promise and have the ```deactivate()``` function take one parameter that will 

It would be useful to allow the user to specify a parent scope. To do parent scopes run ```(config.parentScope || $rootScope).$new()``` instead of ```$rootScope.$new()```. It would also be nice to be able to specify

**Comment by AntJanus** [comment]
That's already part of the directive! You can call `scope.hide`, `scope.show`, and `scope.toggle`.

@circlingthesun what do you mean by results?

**Comment by circlingthesun** [comment]
If I had to select my favourite color inside the modal I need a way of returning it to the calling code.

**Comment by circlingthesun** [comment]
It would be nice to do
```
myColorPickerModal.activate().then(function(favouriteColour){
...
});
```

**Comment by gakimball** [comment]
Nice! We'd like to see this functionality added for notifications too, if possible. Right now there are programmatic notifications, but you need an empty element with the `zf-notification-set` directive to make them work.

**Comment by AntJanus** [comment]
@gakimball That's where I was headed with this next! =D Currently, the prototype already attaches but does not activate, no clue why. But I'm sure I'll get that resolved tomorrow.

**Comment by AntJanus** [comment]
Alright, so I ran into a big-time snag that would prevent the factory from firing off proper `activate` on the modal after its initialization if the code was synchronous. Basically, if we want to default fire the modal by a controller right after it's created, the modal won't even be ready at that point.

I already asked about it on SO since there's not much documentation on it and no SO questions. http://stackoverflow.com/questions/27869320/how-do-you-create-compile-a-directive-via-a-factory

**Comment by AntJanus** [comment]
Phew, got this resolved. For anyone wondering:

$compile seems to run async and thus it's possible to run into severe race conditions. It's possible to preload `scope` for compile with initial data such as activation right from the start. This way, we can tell the modal to compile as an active element! The `foundation.publish()` function will initially publish to an empty subscriber (if the `activate`, `deactivate`, and `toggle` methods were run too early in the app cycle) but that's totally fine! :)

**Comment by AntJanus** [comment]
Improvements:

- [ ] pass data with scope rather than poorly formatted HTML string.
- [ ] create an `init()` function for the modal itself to run against itself at the end of a compilation.

**Comment by AntJanus** [comment]
@circlingthesun The code is pretty much done, can you suggest a way to add this additional functionality? I'm imagining using `$q` and `deffer`; however, if one was to *not* use `then`, I still need the activate function to fire.

**Pull request merged**
